trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: HansvanVeen.azurermdeployment-extension.azurermdeployment-release-task.AzureRmDeployment@1
  displayName: Linux Web App
  inputs:
    azureSubscription: 'Visual Studio Enterprise (4f911ca4-870d-4fb6-894b-6814ecd3776d)'
    resourceLocation: 'east us'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/hanuravim/sandeep/master/WebApp_master.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/hanuravim/sandeep/master/WebApp_Parameters.json'
